# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_sliderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('logo', models.ImageField(upload_to=b'', verbose_name='\u041b\u043e\u0433\u043e\u0442\u0438\u043f')),
            ],
            options={
                'verbose_name': '\u043a\u043e\u043c\u043f\u043e\u0437\u0438\u0442',
                'verbose_name_plural': '\u041a\u043e\u043c\u043f\u043e\u0437\u0438\u0442\u044b',
            },
        ),
    ]
