# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20170226_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a'),
            preserve_default=False,
        ),
    ]
