# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_service_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='full_description',
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(default=' ', verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
            preserve_default=False,
        ),
    ]
