# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20170226_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositetype',
            name='application',
            field=models.TextField(default='', verbose_name='\u041f\u0440\u0438\u043c\u0435\u043d\u0435\u043d\u0438\u0435'),
            preserve_default=False,
        ),
    ]
