# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20170312_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='texture',
            name='big_image',
            field=models.ImageField(default='', upload_to=b'', verbose_name='\u0411\u043e\u043b\u044c\u0448\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
            preserve_default=False,
        ),
    ]
