# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_texture_big_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeSheetOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u0426\u0435\u043d\u0430')),
                ('description', models.TextField(verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u043e\u043f\u0446\u0438\u044f \u043f\u0430\u043d\u0435\u043b\u0438',
                'verbose_name_plural': '\u041e\u043f\u0446\u0438\u0438 \u043f\u0430\u043d\u0435\u043b\u0438',
            },
        ),
        migrations.CreateModel(
            name='CompositeSheetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('width', models.IntegerField(verbose_name='\u0428\u0438\u0440\u0438\u043d\u0430')),
                ('length', models.IntegerField(verbose_name='\u0414\u043b\u0438\u043d\u0430')),
                ('thickness', models.IntegerField(verbose_name='\u0422\u043e\u043b\u0449\u0438\u043d\u0430')),
                ('composite_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.CompositeType')),
            ],
            options={
                'verbose_name': '\u0432\u0438\u0434 \u043f\u0430\u043d\u0435\u043b\u0438',
                'verbose_name_plural': '\u0412\u0438\u0434\u044b \u043f\u0430\u043d\u0435\u043b\u0435\u0439',
            },
        ),
    ]
