# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-08 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sheet_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.IntegerField(),
        ),
    ]
